### ISSUE TITLE
Conflict with wordpress

### ISSUE THREAD

**Issue by NeoCsatornaja** [imankulov/asuggest#10]
The wordpress not like $-selector,please use the <a href="http://api.jquery.com/jQuery.noConflict/">jQuery.noConflict mode</a>

**Comment by imankulov** [comment]
@NeoCsatornaja , as far as I understand, turning off $-variable with `jQuery.noConflict` shouldn't be a job of a library, because noConflict option is something which changes the global state. I think, must of non-wordpress users would be disappointed if my library broke all their $-based code. Instead the library should respect noConflict mode and work nicely without $-variable, which asuggest does. 

Instead, if you plan to include jquery and jquery libraries, I suppose it's up to you to add `jQuery.noConflict();` somewhere in the code to avoid conflict. So far I close the issue, if you disagree, feel free to reopen it.

**Comment by NeoCsatornaja** [comment]
Okey, I understand you.
Have any odds that you make a wordpress version for this?
Just think about it.
How many user use wordpress?
This very big platform for your grate plugin :)
I like to use, but i can't now becouse wordpress shity and hate selectors -.-"
I don't know why :(

**Comment by imankulov** [comment]
@NeoCsatornaja , frankly, I don't see any reason to make a special Wordpress version for the plugin, but nothing prevents you from doing the same, because all you have to do is to add `jQuery.noConflict();` in the beginning of the file, and I don't think it's a big deal worth special version. Good luck :+1:

**Comment by NeoCsatornaja** [comment]
Okey thank you,but sometimes need more configurate.
I tryed textcomplete (made by <a href="https://github.com/yuku-t/jquery-textcomplete/" target="_blank">Yuku</a>) and this configurate not to easy...
I must do somany change becouse,the no conglict mode wasen't enough to wordpress. -.-"
I know the wordpress is a master of pice of shit,have you ever seen him code?
This affull.
Example the ""-cahracters solve is not vaild on commment-tamplete.php(I sucked for this, when i tryed trasnform the reply link to button,for better see)...
And this go some years ago.
So this section not change in 4 years.
You belive it?
If you have time,please test it your plugin in wordpress.
And when you start this testit,you seen this more difficult as looks like.
I hope you understand me,becouse my english a little bad.
Okey most bad :D
