### ISSUE TITLE
Tabbing behavior question

### ISSUE THREAD

**Issue by marcofalcioni** [imankulov/asuggest#4]
Hi,
I would like to use asuggest in a form, where the tab is used to move around fields. 
Is there a way to preserve the tab and use a different key to trigger the suggest cycle?
Thanks
Marco

**Comment by imankulov** [comment]
Currently tab key is hardcoded for making suggestions. I do understand that tab is often used for fields navigation, but honestly I can't imagine what other button can be used instead to provide suggestions. If you send me the patch, I will be happy to revise and incorporate it. Otherwise I will try to add yet another option, but I cannot guarantee that it will be implemented in near future, unfortunately.

**Comment by amgraham** [comment]
I know you have KEY.RIGHT set to insert without a space at the end of the match, but I needed this capability too, so I just changed some bits around and now I can TAB out of the field. I changed KEY.RIGHT to walk through all available options. If I knew anything about GitHub or patches I'd submit a patch to you.

**Comment by imankulov** [comment]
@amgraham, unfortunately, I don't grasp completely what kind of functionality do you need. It would be nice if you would send a patch.

In fact, it is very easy to accomplish with github:
- fork the project (there is a button for this)
- now you can change your local copy, even right in the browser. Click "edit this file" button, and replace the contents of the jquery.asuggest.js file with yours.
- commit (save) your changes and write a meaningful commit message
- make a pull request (there is a button for this too). If you'll be in trouble with the last step, feel free just to write down here that you made a fork and committed your changes

**Comment by amgraham** [comment]
Neat! I'll give that a go tomorrow after work.
On Jan 27, 2012 12:14 AM, "Roman Imankulov" <
reply@reply.github.com>
wrote:

**Comment by amgraham** [comment]
Done and done.

 I think I did it correctly. Time will tell.
